#!/bin/bash
function distrobox(){
sudo touch /etc/subuid && sudo touch /etc/subgid && sudo usermod --add-subuids 165536-231072 --add-subgids 165536-231072 $USER && echo "kernel.unprivileged_userns_clone=1" | sudo tee /etc/sysctl.conf && 
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local && echo -n "container_image="archlinux"
container_manager="podman"" > ~/.distroboxrc && systemctl enable --now --user podman && podman system migrate &&
docker_rootless
}
function docker_rootless(){
curl -fsSL https://get.docker.com/rootless | sh &&
docker_compose
}
function docker_compose(){
curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o ~/bin/docker-compose && chmod a+x ~/bin/docker-compose &&
kubernetes
}
function kubernetes(){
    curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o ~/.local/bin/kubectl &&
    chmod a+x ~/.local/bin/kubectl
    &&
    curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert" -o ~/.local/bin/kubectl-convert &&
    chmod a+x ~/.local/bin/kubectl-convert
    &&
    curl -L https://github.com/kubernetes/kompose/releases/latest/download/kompose-linux-amd64 -o ~/.local/bin/kompose &&
    chmod a+x ~/.local/bin/kompose
}
distrobox
