#!/bin/bash
function gh_bin(){
    echo "visit
https://github.com/cli/cli/releases/, donwload amd64, mv bin to ~/.local/bin/." &&
docker_rootless
}
function docker_rootless(){
sudo touch /etc/subuid && sudo touch /etc/subgid && sudo usermod --add-subuids 165536-231072 --add-subgids 165536-231072 $USER && echo "kernel.unprivileged_userns_clone=1" | sudo tee /etc/sysctl.conf && curl -fsSL https://get.docker.com/rootless | sh &&
docker_compose
}
function docker_compose(){
curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o ~/bin/docker-compose && chmod a+x ~/bin/docker-compose &&
distrobox
}
function distrobox(){
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local && echo -n "container_image="alpine"
container_manager="podman"" > ~/.distroboxrc && systemctl enable --now --user podman && podman system migrate &&
streamlink
}
function streamlink(){
echo -n "visit https://github.com/streamlink/streamlink-appimage/releases/latest/
download to /home/$USER/.local/bin/streamlink (chmod a+x)" &&
ADB
}
function ADB(){
curl -L https://dl.google.com/android/repository/platform-tools-latest-linux.zip -o adb.zip &&
echo "extract,move content platform-tools do /opt/" &&
font_setup
}
function font_setup(){
rm -rf ~/.local/share/fonts/ &&\
mkdir -p ~/.local/share/fonts/ &&\
cd ~/.local/share/fonts &&\
git init &&\
git remote add origin https://github.com/vmath3us/packfonts.git &&\ 
git fetch &&\
git checkout origin/main
}
gh_bin
