#!/bin/bash
function docker_rootless(){
sudo touch /etc/subuid && sudo touch /etc/subgid && sudo usermod --add-subuids 165536-231072 --add-subgids 165536-231072 $USER && echo "kernel.unprivileged_userns_clone=1" | sudo tee /etc/sysctl.conf && curl -fsSL https://get.docker.com/rootless | sh &&
docker_compose
}
function docker_compose(){
curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o ~/bin/docker-compose && chmod a+x ~/bin/docker-compose && distrobox
}
function distrobox(){
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local && echo -n "container_image="archlinux"
container_manager="podman"" > ~/.distroboxrc && systemctl enable --now podman && podman system migrate &&
yt_dlp
}
function yt_dlp(){
curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o ~/.local/bin/yt-dlp && chmod a+x ~/.local/bin/yt-dlp &&
streamlink
}
function streamlink (){
echo -n "visit https://github.com/streamlink/streamlink-appimage/releases/latest/
download to /home/$USER/.local/bin/streamlink (chmod a+x)" &&
ADB
}
function ADB(){
curl -L https://dl.google.com/android/repository/platform-tools-latest-linux.zip -o ~/Documents/adb.zip &&
echo "extract,move content platform-tools do /opt/" &&
fzf
}
function fzf(){
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
~/.fzf/install &&
nerd_fonts
}
function nerd_fonts(){
mkdir -p ~/.local/share/fonts && cd ~/.local/share/fonts && rm -rf .* ; rm -rf * ; git init && git remote add origin https://github.com/vmath3us/packfonts.git && git fetch && git checkout origin/main &&
exit 0
}
docker_rootless
