#!/bin/zsh
function oh-my-zsh(){
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && export $?=1 &&
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions &&
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting &&
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
~/.fzf/install &&
mkdir -p ~/.local/share/fonts && cd ~/.local/share/fonts && rm -rf .* ; rm -rf * ; git init && git remote add origin https://github.com/vmath3us/packfonts.git && git fetch && git checkout origin/main &&
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k && cp zshrc ~/.zshrc && source ~/.zshrc
}

